//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoTransparencia
    {
        public CatalogoTransparencia()
        {
            this.MapeosReportes = new HashSet<MapeosReporte>();
        }
    
        public System.Guid CT_NodoId { get; set; }
        public Nullable<System.Guid> CT_NodoPadreId { get; set; }
        public string CT_Descripcion { get; set; }
        public string CT_Texto { get; set; }
        public Nullable<System.Guid> CT_CMTR_TipoRangoId { get; set; }
        public Nullable<int> CT_Rango { get; set; }
        public bool CT_Activo { get; set; }
        public bool CT_Sistema { get; set; }
        public bool CT_Aplica { get; set; }
        public int CT_Orden { get; set; }
        public Nullable<System.DateTime> CT_FechaUltimaModificacion { get; set; }
        public Nullable<System.Guid> CT_USU_ModificadoPorId { get; set; }
        public byte[] CT_Timestamp { get; set; }
    
        public virtual ControlesMaestrosTiposRango ControlesMaestrosTiposRango { get; set; }
        public virtual ICollection<MapeosReporte> MapeosReportes { get; set; }
    }
}
namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoTransparenciaReporte
    {
        public System.Guid CTR_ReporteId { get; set; }
        public System.Guid CTR_MR_MapeoId { get; set; }
        public string CTR_NombreArchivo { get; set; }
        public string CTR_DescripcionArchivo { get; set; }
        public Nullable<System.DateTime> CTR_FechaInicio { get; set; }
        public System.DateTime CTR_FechaFin { get; set; }
        public bool CTR_Visible { get; set; }
        public bool CTR_Borrado { get; set; }
        public System.DateTime CTR_FechaRegistro { get; set; }
        public System.Guid CTR_USU_SubidoPorId { get; set; }
        public System.DateTime CTR_FechaUltimaModificacion { get; set; }
        public System.Guid CTR_USU_ModificadoPorId { get; set; }
        public byte[] CTR_Timestamp { get; set; }
    
        public virtual MapeosReporte MapeosReporte { get; set; }
    }
}
namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlesMaestro
    {
        public System.Guid CMA_ControlId { get; set; }
        public string CMA_Control { get; set; }
        public string CMA_Valor { get; set; }
        public System.DateTime CMA_FechaUltimaModificacion { get; set; }
        public System.Guid CMA_USU_ModificadoPorId { get; set; }
        public byte[] CMA_Timestamp { get; set; }
    }
}
namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlesMaestrosTiposRango
    {
        public ControlesMaestrosTiposRango()
        {
            this.CatalogoTransparencias = new HashSet<CatalogoTransparencia>();
        }
    
        public System.Guid CMTR_TipoRangoId { get; set; }
        public string CMTR_TipoRango { get; set; }
        public byte[] CMTR_Timestamp { get; set; }
    
        public virtual ICollection<CatalogoTransparencia> CatalogoTransparencias { get; set; }
    }
}
namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapeosReporte
    {
        public MapeosReporte()
        {
            this.CatalogoTransparenciaReportes = new HashSet<CatalogoTransparenciaReporte>();
        }
    
        public System.Guid MR_MapeoId { get; set; }
        public string MR_RutaFisicaReporte { get; set; }
        public System.Guid MR_CT_NodoId { get; set; }
        public string MR_Prefijo { get; set; }
        public byte[] MR_Timestamp { get; set; }
    
        public virtual CatalogoTransparencia CatalogoTransparencia { get; set; }
        public virtual ICollection<CatalogoTransparenciaReporte> CatalogoTransparenciaReportes { get; set; }
    }
}
namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public System.Guid USU_UsuarioId { get; set; }
        public string USU_NombreUsuario { get; set; }
        public string USU_CorreoElectronico { get; set; }
        public string USU_Contrasenia { get; set; }
        public bool USU_Activo { get; set; }
        public System.Guid USU_RegistradoPor { get; set; }
        public System.DateTime USU_FechaRegistro { get; set; }
        public byte[] USU_Timestamp { get; set; }
    }
}
namespace EntityModel
{
    using System;
    
    public partial class ArbolCatalogoTransparencia
    {
        public System.Guid CT_NodoId { get; set; }
        public Nullable<System.Guid> CT_NodoPadreId { get; set; }
        public string CT_Descripcion { get; set; }
        public bool CT_Aplica { get; set; }
        public string CT_Orden { get; set; }
    }
}
namespace EntityModel
{
    using System;
    
    public partial class ListadoArchivos
    {
        public bool CTR_Selected { get; set; }
        public System.Guid CTR_ReporteId { get; set; }
        public string MR_RutaFisicaReporte { get; set; }
        public string CTR_DescripcionArchivo { get; set; }
        public string CTR_ExtensionArchivo { get; set; }
    }
}
